FROM python:3.14-slim

LABEL scenario=python-pipelining

# Smell: not the correct folder, should be /app
WORKDIR app

COPY requirements/base.txt /app/requirements.txt

RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get clean

RUN pip install -r /app/requirements.txt

COPY . .

EXPOSE 8080
# Smell: not the correct form, should be ENTRYPOINT ["uvicorn", "app.main:app"...]
ENTRYPOINT uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
