# Based on Sebastián Ramírez uvicorn containers, see: https://github.com/tiangolo/uvicorn-gunicorn-starlette-docker


# ARGS at this level referenced only by FROMs
ARG TIANGOLO_TAG=python3.8-alpine3.10

# --------------------------------------
# Build dependencies in build stage
# --------------------------------------
FROM tiangolo/uvicorn-gunicorn:${TIANGOLO_TAG} as builder
ARG REQUIREMENTS=production

ENV PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100
    
WORKDIR /app

# Cache installed dependencies between builds
COPY ./requirements ./requirements/
RUN pip install -r ./requirements/${REQUIREMENTS}.txt --user

# --------------------------------------
# Create final container loaded with app
# --------------------------------------

FROM tiangolo/uvicorn-gunicorn:${TIANGOLO_TAG}

LABEL scenario=python-pipelining

ENV USER=docker GROUP=docker \
    UID=12345 GID=23456 \
    HOME=/app PYTHONUNBUFFERED=1

# Create user/group
RUN addgroup --gid "${GID}" "${GROUP}" \
    && adduser \
    --disabled-password \
    --gecos "" \
    --home "$(pwd)" \
    --ingroup "${GROUP}" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"

WORKDIR ${HOME}

# TODO - currently can only get uvicorn to work as root - open for suggestions
# USER ${USER}

COPY --from=builder /root/.local /usr/local
COPY --chown=${USER}:${GROUP} . .

ENV PORT 8080
EXPOSE 8080
