FROM python:3.8-slim

LABEL scenario=python-pipelining

WORKDIR app

COPY requirements/base.txt /app/requirements.txt

RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get clean

RUN pip install -r /app/requirements.txt

# && rm -rf /root/.cache/pip

COPY . .

EXPOSE 8080
ENTRYPOINT uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
