apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: application-pipeline-run
spec:
  pipelineRef:
    name: application-pipeline
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  params:
    - name: repo-url
      value: https://github.com/javajon/mountains-service-pi
    - name: revision
      value: master
    - name: pathToContext
      value: .
    - name: pathToYamlFile
      value: deploy.yaml
    - name: pathToDockerfile
      value: Dockerfile-slim
    - name: imageUrl
      value: mountains
    - name: imageTag
      value: "0.0.1"
  serviceAccountName: service-account
